#!/usr/bin/env python3
"""Generate local AIS Bench configs for bundled GPQA and GSM8K data."""

import argparse
import copy
import csv
import importlib.util
import json
import math
import os
from pathlib import Path
from pprint import pformat
import shlex
import string
import subprocess
import sys
from urllib.parse import urlsplit, urlunsplit

from acc_len import metrics_url, report_acc_len


# Locate this file, never the caller's working directory or ais_bench installation.
ROOT = Path(__file__).resolve().parent
SUBSETS = ("diamond", "main", "extended")
DATASET_SUBSETS = {"gpqa": SUBSETS, "gsm8k": ("test",)}
MODEL_TYPE = "ais_bench.benchmark.models.VLLMCustomAPIChat"
POSTPROCESSOR = (
    "ais_bench.benchmark.utils.postprocess.model_postprocessors."
    "extract_non_reasoning_content"
)
HEADER = "# Generated by run_gpqa.py. Change settings.json or CLI arguments to regenerate.\n"


def read_json(path):
    with path.open(encoding="utf-8-sig") as handle:
        return json.load(handle)


def resolve_tool_path(value, root):
    """Resolve relative resources inside the tool; keep explicit absolute paths."""
    return (root / Path(value).expanduser()).resolve()


def json_object(value, root):
    """Accept inline JSON or @file; never evaluate Python expressions."""
    try:
        result = read_json(resolve_tool_path(value[1:], root)) if value.startswith("@") else json.loads(value)
    except (OSError, ValueError) as exc:
        raise argparse.ArgumentTypeError(f"Invalid JSON: {exc}") from exc
    if not isinstance(result, dict):
        raise argparse.ArgumentTypeError("Expected a JSON object")
    return result


def merge(target, overrides):
    for key, value in overrides.items():
        if isinstance(value, dict) and isinstance(target.get(key), dict):
            merge(target[key], value)
        else:
            target[key] = copy.deepcopy(value)


def parser(root=None):
    root = ROOT if root is None else root
    result = argparse.ArgumentParser(
        description="Run bundled GPQA or GSM8K with installed ais_bench; all generated files stay in this folder.",
        epilog="Extra ais_bench options: append -- followed by those options. See README.md for examples.",
        allow_abbrev=False,
    )
    result.add_argument("--settings", type=Path,
                        help="JSON overrides; relative paths resolve inside this tool folder")
    result.add_argument("--generate-only", "--dry-run", action="store_true",
                        help="Validate local data, write configs and print command without running ais_bench")
    result.add_argument("--model", help="Served model name (empty = detected by ais_bench)")
    result.add_argument("--host-ip", "--host", dest="host_ip")
    result.add_argument("--host-port", "--port", dest="host_port", type=int)
    result.add_argument("--url", help="Service URL; /v1 or /v1/chat/completions suffixes are accepted")
    result.add_argument("--api-key", help="Service API key; also accepts AIS_BENCH_API_KEY environment variable")
    result.add_argument("--abbr", help="Model abbreviation used in result filenames")
    result.add_argument("--path", help="Local tokenizer path; relative paths resolve inside this tool folder")
    for name in ("max-out-len", "batch-size", "retry"):
        result.add_argument("--" + name, type=int)
    result.add_argument("--request-rate", type=float)
    for name in ("stream", "use-timestamp", "trust-remote-code"):
        result.add_argument("--" + name, action=argparse.BooleanOptionalAction, default=None)
    result.add_argument("--temperature", type=float)
    result.add_argument("--ignore-eos", action=argparse.BooleanOptionalAction, default=None)
    result.add_argument("--generation-kwargs", type=lambda value: json_object(value, root),
                        help='Merge JSON or @file (relative to this tool folder), e.g. \'{"top_p":0.95}\'')
    result.add_argument("--set", action="append", default=[], metavar="KEY=VALUE",
                        help="Set a model field (repeatable); dotted keys and JSON values supported")
    result.add_argument("--dataset", choices=tuple(DATASET_SUBSETS),
                        help="Dataset to evaluate (default: gpqa; gsm8k uses the test split)")
    result.add_argument("--subset", nargs="+", choices=(*SUBSETS, "test", "all"),
                        help="GPQA: diamond/main/extended; GSM8K: test; all selects this dataset's subsets")
    result.add_argument("--prompt", choices=("cot", "str"))
    result.add_argument("--mode", choices=("all", "infer", "eval", "viz", "perf", "perf_viz"))
    result.add_argument("--num-prompts", type=int, help="Use only the first N questions of each selected subset")
    result.add_argument("--debug", action=argparse.BooleanOptionalAction, default=None)
    result.add_argument("--dump-eval-details", action=argparse.BooleanOptionalAction, default=None)
    result.add_argument("--reuse", nargs="?", const="latest", help="Reuse latest outputs or a given run timestamp")
    result.add_argument("--acc-len", action=argparse.BooleanOptionalAction, default=None,
                        help="Collect acceptance length after successful all/infer runs (default: enabled)")
    result.add_argument("--num-spec", "--num-speculative-tokens", dest="num_spec", type=int,
                        help="Server's speculative token count; inferred from metric positions when omitted")
    result.add_argument("--metrics-url", help="Override the default model service /metrics endpoint")
    result.add_argument("--metrics-timeout", type=float, help="Metrics request timeout in seconds (default: 10)")
    return result


def apply_set(model, assignment):
    key, separator, raw = assignment.partition("=")
    parts = key.split(".")
    if not separator or not all(part.isidentifier() for part in parts):
        raise ValueError(f"Invalid --set {assignment!r}; expected field=value or generation_kwargs.field=value")
    try:
        value = json.loads(raw)
    except ValueError:
        value = raw
    current = model
    for part in parts[:-1]:
        current = current.setdefault(part, {})
        if not isinstance(current, dict):
            raise ValueError(f"Cannot set nested field {key}: parent is not an object")
    current[parts[-1]] = value


def normalize_url(value, enable_ssl=False):
    if not value:
        return ""
    protocol = "https://" if enable_ssl else "http://"
    parsed = urlsplit(value if "://" in value else protocol + value)
    if parsed.scheme not in ("http", "https") or not parsed.hostname or parsed.query or parsed.fragment:
        raise ValueError("url must be an HTTP(S) service URL without query parameters or fragments")
    # AIS Bench appends v1/chat/completions itself. Preserve reverse-proxy prefixes.
    path = parsed.path.rstrip("/")
    for suffix in ("/v1/chat/completions", "/v1"):
        if path.endswith(suffix):
            path = path[:-len(suffix)]
            break
    return urlunsplit((parsed.scheme, parsed.netloc, path + "/", "", ""))


def check_number(mapping, key, minimum, maximum=None, integer=False):
    value = mapping.get(key)
    expected = int if integer else (int, float)
    if (isinstance(value, bool) or not isinstance(value, expected)
            or not math.isfinite(value) or value < minimum
            or (maximum is not None and value > maximum)):
        limit = f"{minimum}..{maximum}" if maximum is not None else f">= {minimum}"
        raise ValueError(f"{key} must be a finite {'integer' if integer else 'number'} {limit}")


def load_settings(args, root):
    settings = read_json(root / "settings.json")
    if not isinstance(settings, dict):
        raise ValueError("settings.json must contain a JSON object")
    metric_defaults = dict(enabled=True, num_speculative_tokens=None, metrics_url="", timeout=10)
    if not isinstance(settings.get("acc_len", {}), dict):
        raise ValueError("acc_len must be a JSON object")
    merge(metric_defaults, settings.get("acc_len", {}))
    settings["acc_len"] = metric_defaults
    if args.settings:
        override = read_json(resolve_tool_path(args.settings, root))
        if not isinstance(override, dict):
            raise ValueError("--settings must contain a JSON object")
        dataset_override = override.get("dataset")
        if isinstance(dataset_override, dict) and isinstance(settings.get("dataset"), dict):
            previous_name = settings["dataset"].get("name", "gpqa")
            if dataset_override.get("name", previous_name) != previous_name and "subsets" not in dataset_override:
                # A new dataset must not inherit the previous dataset's split names.
                settings["dataset"].pop("subsets", None)
        merge(settings, override)
    if set(settings) != {"model", "dataset", "run", "acc_len"}:
        raise ValueError("settings.json must contain only model, dataset, run and acc_len objects")
    if not all(isinstance(value, dict) for value in settings.values()):
        raise ValueError("model, dataset, run and acc_len must be JSON objects")
    model, dataset, run = (settings[name] for name in ("model", "dataset", "run"))
    if "AIS_BENCH_API_KEY" in os.environ:
        model["api_key"] = os.environ["AIS_BENCH_API_KEY"]
    for key in ("model", "host_ip", "host_port", "url", "api_key", "abbr", "path",
                "max_out_len", "batch_size", "retry", "request_rate", "stream",
                "use_timestamp", "trust_remote_code"):
        if getattr(args, key) is not None:
            model[key] = getattr(args, key)
    generation = model.get("generation_kwargs")
    if not isinstance(generation, dict):
        raise ValueError("generation_kwargs must be a JSON object")
    if args.generation_kwargs is not None:
        merge(generation, args.generation_kwargs)
    for key in ("temperature", "ignore_eos"):
        if getattr(args, key) is not None:
            generation[key] = getattr(args, key)
    for assignment in args.set:
        apply_set(model, assignment)
    for key in ("mode", "num_prompts", "debug", "dump_eval_details"):
        if getattr(args, key) is not None:
            run[key] = getattr(args, key)
    dataset.setdefault("name", "gpqa")
    if args.dataset is not None and args.dataset != dataset["name"]:
        dataset["name"] = args.dataset
        dataset.pop("subsets", None)
    dataset_name = dataset["name"]
    if not isinstance(dataset_name, str) or dataset_name not in DATASET_SUBSETS:
        raise ValueError("dataset.name must be gpqa or gsm8k")
    allowed_subsets = DATASET_SUBSETS[dataset_name]
    if args.subset is not None:
        dataset["subsets"] = args.subset
    if args.prompt is not None:
        dataset["prompt"] = args.prompt
    subsets = dataset.get("subsets", [allowed_subsets[0]])
    if not isinstance(subsets, list) or not subsets or any(s not in (*allowed_subsets, "all") for s in subsets):
        choices = ", ".join((*allowed_subsets, "all"))
        raise ValueError(f"dataset.subsets for {dataset_name} must be a nonempty list of {choices}")
    dataset["subsets"] = list(allowed_subsets) if "all" in subsets else list(dict.fromkeys(subsets))
    if dataset.get("prompt") not in ("cot", "str"):
        raise ValueError("dataset.prompt must be cot or str")
    if run.get("mode") not in ("all", "infer", "eval", "viz", "perf", "perf_viz"):
        raise ValueError("Invalid run.mode")
    for key in ("debug", "dump_eval_details"):
        if not isinstance(run.get(key), bool):
            raise ValueError(f"run.{key} must be a boolean")
    if run.get("num_prompts") is not None:
        check_number(run, "num_prompts", 1, integer=True)
    for key, minimum, maximum in (("host_port", 1, 65535), ("max_out_len", 1, None),
                                   ("batch_size", 1, 100000), ("retry", 0, 1000)):
        check_number(model, key, minimum, maximum, integer=True)
    check_number(model, "request_rate", 0, 64000)
    for key in ("stream", "use_timestamp", "trust_remote_code", "enable_ssl", "verbose"):
        if not isinstance(model.get(key, False), bool):
            raise ValueError(f"{key} must be a boolean")
    for key in ("abbr", "path", "model", "api_key", "host_ip", "url"):
        if not isinstance(model.get(key), str):
            raise ValueError(f"{key} must be a string")
    if not model["abbr"] or any(c in model["abbr"] for c in '/\\:*?"<>|') or model["abbr"] in (".", ".."):
        raise ValueError("abbr must be a nonempty filename-safe name")
    generation = model["generation_kwargs"]
    if not isinstance(generation, dict):
        raise ValueError("generation_kwargs must be a JSON object")
    if "temperature" in generation:
        check_number(generation, "temperature", 0)
    if "ignore_eos" in generation and not isinstance(generation["ignore_eos"], bool):
        raise ValueError("ignore_eos must be a boolean")
    if model.get("attr", "service") != "service" or model.get("type", MODEL_TYPE) != MODEL_TYPE:
        raise ValueError("This tool uses attr=service and VLLMCustomAPIChat")
    model["attr"] = "service"
    model["type"] = MODEL_TYPE
    model.setdefault("pred_postprocessor", {"type": POSTPROCESSOR})
    model["url"] = normalize_url(model["url"], model.get("enable_ssl", False))
    metric_options = settings["acc_len"]
    for option, field in (("acc_len", "enabled"), ("num_spec", "num_speculative_tokens"),
                          ("metrics_url", "metrics_url"), ("metrics_timeout", "timeout")):
        if getattr(args, option) is not None:
            metric_options[field] = getattr(args, option)
    if not isinstance(metric_options.get("enabled"), bool):
        raise ValueError("acc_len.enabled must be a boolean")
    if metric_options.get("num_speculative_tokens") is not None:
        check_number(metric_options, "num_speculative_tokens", 1, integer=True)
    check_number(metric_options, "timeout", 0)
    if metric_options["timeout"] == 0:
        raise ValueError("acc_len.timeout must be positive")
    if not isinstance(metric_options.get("metrics_url"), str):
        raise ValueError("acc_len.metrics_url must be a string")
    metrics_url(model, metric_options["metrics_url"])
    if model["path"]:
        model["path"] = str(resolve_tool_path(model["path"], root))
        if not Path(model["path"]).exists():
            raise ValueError(f"Tokenizer path does not exist: {model['path']}")
    # Reject NaN/Infinity also in arbitrary JSON options before writing Python.
    json.dumps(settings, allow_nan=False)
    return settings


def validate_gsm8k_data(root):
    counts = {}
    # AIS Bench's GSM8KDataset loads both files, even for zero-shot test evaluation.
    for split in ("train", "test"):
        path = root / "data" / "gsm8k" / f"{split}.jsonl"
        if not path.is_file():
            raise ValueError(f"Missing bundled dataset: {path}. Copy the complete gpqa_runner folder including data/.")
        count = 0
        with path.open(encoding="utf-8") as handle:
            for count, line in enumerate(handle, 1):
                try:
                    row = json.loads(line)
                    if (not isinstance(row, dict)
                            or any(not isinstance(row.get(key), str) or not row[key].strip()
                                   for key in ("question", "answer"))):
                        raise ValueError("question and answer must be nonempty strings")
                    parts = row["answer"].split("#### ")
                    if len(parts) != 2:
                        raise ValueError("answer must end with #### followed by a number")
                    int(parts[1].replace(",", "").strip())
                except ValueError as exc:
                    raise ValueError(f"Invalid GSM8K record at {path}:{count}: {exc}") from exc
        if count == 0:
            raise ValueError(f"Empty GSM8K dataset: {path}")
        counts[split] = count
    return {"test": counts["test"]}


def validate_data(root, subsets, dataset_name="gpqa"):
    if dataset_name == "gsm8k":
        return validate_gsm8k_data(root)
    counts = {}
    columns = ["Question", "Correct Answer", "Incorrect Answer 1", "Incorrect Answer 2", "Incorrect Answer 3"]
    for subset in subsets:
        path = root / "data" / "gpqa" / f"gpqa_{subset}.csv"
        if not path.is_file():
            raise ValueError(f"Missing bundled dataset: {path}. Copy the complete gpqa_runner folder including data/.")
        with path.open(encoding="utf-8", newline="") as handle:
            rows = csv.reader(handle)
            header = next(rows, [])
            if header[7:12] != columns:
                raise ValueError(f"Invalid GPQA CSV header: {path}")
            count = 0
            for count, row in enumerate(rows, 1):
                if len(row) < 12 or any(not value.strip() for value in row[7:12]):
                    raise ValueError(f"Invalid GPQA question at record {count}: {path}")
            if count == 0:
                raise ValueError(f"Empty GPQA dataset: {path}")
            counts[subset] = count
    return counts


def dataset_configs(root, settings):
    dataset_name = settings.get("name", "gpqa")
    prompt_mode = settings["prompt"]
    prompt_dir = root / "prompts"
    if dataset_name == "gsm8k":
        prompt_dir /= "gsm8k"
    prompt = (prompt_dir / f"{prompt_mode}.txt").read_text(encoding="utf-8").strip()
    fields = {field for _, field, _, _ in string.Formatter().parse(prompt) if field is not None}
    required_fields = {"question"} if dataset_name == "gsm8k" else {"question", "A", "B", "C", "D"}
    if fields != required_fields:
        placeholders = ", ".join("{" + field + "}" for field in sorted(required_fields))
        raise ValueError(f"Prompt must contain exactly the placeholders {placeholders}")
    template = {"round": [{"role": "HUMAN", "prompt": prompt}]} if prompt_mode == "cot" else prompt
    if dataset_name == "gsm8k":
        return [dict(
            abbr="gsm8k",
            type="ais_bench.benchmark.datasets.GSM8KDataset",
            path=str((root / "data" / "gsm8k").resolve()),
            reader_cfg=dict(input_columns=["question"], output_column="answer", test_split="test"),
            infer_cfg=dict(
                prompt_template=dict(type="ais_bench.benchmark.openicl.icl_prompt_template.PromptTemplate",
                                     template=template),
                retriever=dict(type="ais_bench.benchmark.openicl.icl_retriever.ZeroRetriever"),
                inferencer=dict(type="ais_bench.benchmark.openicl.icl_inferencer.GenInferencer"),
            ),
            eval_cfg=dict(
                evaluator=dict(type="ais_bench.benchmark.datasets.Gsm8kEvaluator"),
                pred_postprocessor=dict(type="ais_bench.benchmark.datasets.gsm8k_postprocess"),
                dataset_postprocessor=dict(type="ais_bench.benchmark.datasets.gsm8k_dataset_postprocess"),
            ),
        )]
    postprocessor = {"type": "ais_bench.benchmark.datasets.GPQA_Simple_Eval_postprocess"}
    if prompt_mode == "str":
        postprocessor = {
            "type": "ais_bench.benchmark.utils.postprocess.text_postprocessors.first_option_postprocess",
            "options": "ABCD",
        }
    return [
        dict(
            abbr=f"GPQA_{subset}",
            type="ais_bench.benchmark.datasets.GPQADataset",
            path=str((root / "data" / "gpqa").resolve()),
            name=f"gpqa_{subset}.csv",
            reader_cfg=dict(input_columns=["question", "A", "B", "C", "D"], output_column="answer"),
            infer_cfg=dict(
                prompt_template=dict(type="ais_bench.benchmark.openicl.icl_prompt_template.PromptTemplate", template=template),
                retriever=dict(type="ais_bench.benchmark.openicl.icl_retriever.ZeroRetriever"),
                inferencer=dict(type="ais_bench.benchmark.openicl.icl_inferencer.GenInferencer"),
            ),
            eval_cfg=dict(evaluator=dict(type="ais_bench.benchmark.datasets.GPQAEvaluator"),
                          pred_postprocessor=postprocessor),
        ) for subset in settings["subsets"]
    ]


def generate_configs(root, settings):
    dataset_name = settings["dataset"].get("name", "gpqa")
    datasets = dataset_configs(root, settings["dataset"])
    models_text = "models = " + pformat([settings["model"]], width=100, sort_dicts=False) + "\n"
    datasets_var = f"{dataset_name}_datasets"
    datasets_text = datasets_var + " = " + pformat(datasets, width=100, sort_dicts=False) + "\n"
    config_dir = root / "configs"
    model_path = config_dir / "models" / "vllm_api" / "vllm_api_general_chat.py"
    dataset_path = config_dir / "datasets" / dataset_name / f"{dataset_name}_local.py"
    combined_path = config_dir / f"{dataset_name}_benchmark.py"
    files = {
        model_path: HEADER + models_text,
        dataset_path: HEADER + datasets_text,
        combined_path: HEADER + models_text + "\n" + datasets_text +
        f"\ndatasets = {datasets_var}\nsummarizer = dict(attr='accuracy')\n",
    }
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return combined_path


def build_command(root, config_path, settings, args, extra):
    run = settings["run"]
    command = [sys.executable, "-m", "ais_bench.benchmark.cli.main", str(config_path),
               "--mode", run["mode"], "--work-dir", str(root / "outputs")]
    if run.get("num_prompts") is not None:
        command += ["--num-prompts", str(run["num_prompts"])]
    for key in ("debug", "dump_eval_details"):
        if run[key]:
            command.append("--" + key.replace("_", "-"))
    if args.reuse is not None:
        command += ["--reuse", args.reuse]
    return command + extra


def should_collect_acc_len(settings, extra):
    # Honor mode/dry-run overrides forwarded to ais_bench after the separator.
    check = argparse.ArgumentParser(add_help=False, allow_abbrev=False)
    check.add_argument("--mode", "-m", default=settings["run"]["mode"])
    check.add_argument("--dry-run", action="store_true")
    check.add_argument("--search", "-s", action="store_true")
    check.add_argument("--help", "-h", action="store_true")
    args, _ = check.parse_known_args(extra)
    return (settings["acc_len"]["enabled"] and args.mode in ("all", "infer")
            and not (args.dry_run or args.search or args.help))


def main(argv=None):
    cli = parser()
    argv = list(sys.argv[1:] if argv is None else argv)
    separator = argv.index("--") if "--" in argv else len(argv)
    args = cli.parse_args(argv[:separator])
    extra = argv[separator + 1:]
    try:
        settings = load_settings(args, ROOT)
        dataset_name = settings["dataset"]["name"]
        counts = validate_data(ROOT, settings["dataset"]["subsets"], dataset_name)
        config_path = generate_configs(ROOT, settings)
        command = build_command(ROOT, config_path, settings, args, extra)
        print(f"Tool directory: {ROOT}", flush=True)
        print(f"Local {dataset_name.upper()}: " + ", ".join(f"{name}={count}" for name, count in counts.items()), flush=True)
        print(f"Config: {config_path}\nResults: {ROOT / 'outputs'}", flush=True)
        printable = subprocess.list2cmdline(command) if os.name == "nt" else shlex.join(command)
        print(f"Command: {printable}", flush=True)
        if args.generate_only:
            return 0
        if importlib.util.find_spec("ais_bench") is None:
            raise ValueError("ais_bench is not installed in this Python environment. Activate the environment "
                             "containing ais_bench and run this script again. Configs have been generated.")
        env = os.environ.copy()
        env["PYTHONDONTWRITEBYTECODE"] = "1"
        env.setdefault("HF_HOME", str(ROOT / ".cache" / "huggingface"))
        env.setdefault("HF_DATASETS_CACHE", str(ROOT / ".cache" / "datasets"))
        returncode = subprocess.run(command, cwd=str(ROOT), env=env, check=False).returncode
        if returncode == 0 and should_collect_acc_len(settings, extra):
            report_acc_len(settings["model"], settings["acc_len"], ROOT / "outputs" / "acc_len",
                           context=dict(model=settings["model"]["model"],
                                        dataset=dataset_name,
                                        subsets=settings["dataset"]["subsets"],
                                        num_prompts=settings["run"]["num_prompts"]))
        return returncode
    except (OSError, ValueError, csv.Error) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
